### ISSUE TITLE
Create SpeciesListServerArchive guide

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/phylo_services_docs#1]
A description about the structure of the archive file to upload species list.

**Comment by arlin** [comment]
Moving this back to ready, re-assigning to Dail so that he can describe the new format.

**Comment by hdliv** [comment]
moving this to in review since we have revised the description with @abusalehmdtayeen

**Comment by arlin** [comment]
I made a few minor changes to the wording, and fixed the dates in the examples so that they conform to ISO.  

I have two questions.   
1.  The description says that header lines are not required.  If there is no header, then do we assume the standard columns in standard order?   Or, is a metafile  required to parse the csv files when there are no header lines?  This should be clarified.  
2.  Do we assume that the files are named "species.csv" and "list.csv", unless the metafile says otherwise?   If so, this should be stated.   It seems to me that the metafile **must** have a fixed name like "metafile.xml", or it must be the only XML file in the archive, otherwise how would the parser know where to start?

**Comment by abusalehmdtayeen** [comment]
@arlin : 
1. The standard of both files (species and list) is given in the example section of the guide. That means user has to use standard headers and standard order of columns that we have defined. If the user does not want to use headers or want to use different order of columns, he must create the meta-file. In the meta-file, there is an option for the user to specify that whether the files contain headers or not. Also he can mention his own order for the columns.
2. Yes, if meta-file is created, user can specify the file names. Otherwise, he has to use the default file names ("species.csv" and "list.csv"). 
The name of the meta-file can be anything as long as this is the only .xml file in the archive. Or we can force the user to use a default name like "metafile.xml".

Reading content of the files from archive according to the data provided  in the xml file must be implemented in the upload section of Van's (@ducvan0212) portal.

**Comment by arlin** [comment]
OK, I made a few changes to clarify the text and clsoed this.
